# Atari TOS

TARGET = vlink.ttp
DIR = TOS
MD = mkdir
RM = rm -f

CC = vc +tos
CCOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
COPTS = -c99 -c -O1 -DATARI
CONFIG =

LD = vc +tos
LDOUT = -o $(DUMMYVARIABLE)	# produces the string "-o "
LDOPTS =
LIBS =


include make.rules
